// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNamePortfolioVisit = "portfolio.visit"

// PortfolioVisit mapped from table <portfolio.visit>
type PortfolioVisit struct {
	ID                  int64     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	Source              string    `gorm:"column:source;not null" json:"source"`
	Referrer            string    `gorm:"column:referrer;not null" json:"referrer"`
	UserAgent           string    `gorm:"column:user_agent" json:"user_agent"`
	IP                  string    `gorm:"column:ip" json:"ip"`
	VisitCount          int32     `gorm:"column:visit_count" json:"visit_count"`
	GithubVisitCount    int32     `gorm:"column:github_visit_count" json:"github_visit_count"`
	LinkedinVisitCount  int32     `gorm:"column:linkedin_visit_count" json:"linkedin_visit_count"`
	ResumeDownloadCount int32     `gorm:"column:resume_download_count" json:"resume_download_count"`
	CreatedAt           time.Time `gorm:"column:created_at;default:CURRENT_TIMESTAMP" json:"created_at"`
	UpdatedAt           time.Time `gorm:"column:updated_at;default:CURRENT_TIMESTAMP" json:"updated_at"`
}

// TableName PortfolioVisit's table name
func (*PortfolioVisit) TableName() string {
	return TableNamePortfolioVisit
}
